{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/{{ $name }}-irsa-role"
---
{{- end }}
